name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15.5-alpine
        env:
          POSTGRES_DB: healenium
          POSTGRES_USER: healenium_user
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        ports:
          - 5433:5432
        options: >-
          --health-cmd "pg_isready -U healenium_user -d healenium"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        run: |
          docker --version
          docker compose version

      - name: Start services with Docker Compose
        run: docker compose -f infraa/docker-compose.yaml up -d

      - name: Wait for PostgreSQL to be ready
        run: |
          echo "Waiting for PostgreSQL..."
          until docker exec postgres1-db pg_isready -U healenium_user -d healenium; do
            sleep 2;
          done
          echo "PostgreSQL is ready!"

      - name: Run tests
        run: mvn test
